INSERT INTO survivor VALUES (1, 'Wilson', 'The Gentleman Scientist', 'At heart Wilson is truly a man of science. It''s not in his nature to resist the call of the unknown.', 'I will conquer this world with the power of my MIND!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wilson.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wilson.png', 'April 23', 'Bacon and Eggs', 'Slim', 150, 150, 200);
INSERT INTO survivor VALUES (2, 'Willow', 'The Firestarter', 'Willow is a candid woman whose penchant for fire often gets her into more than a little trouble.', 'All will bathe in the prettiest of flames.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Willow.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Willow.png', 'May 7', 'Spicy Chili', 'Slim', 150, 150, 120);
INSERT INTO survivor VALUES (3, 'Wolfgang', 'The Strongman', 'Wolfgang is an affable, musclebound giant with a heart plagued by a myriad of phobias.', 'I am mighty! No one is mightier!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wolfgang.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wolfgang.png', 'October 2', 'Roast Potato', 'Grim', 200, 200, 200);
INSERT INTO survivor VALUES (4, 'Wendy', 'The Bereaved', 'Wendy is a morose young lady with a sisterly bond so powerful, it transcends death itself.', 'Abigail? Come back! I''m not done playing with you.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wendy.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wendy.png', 'November 11', 'Banana Pop', 'Slim', 150, 150, 200);
INSERT INTO survivor VALUES (5, 'WX-78', 'The Soulless Automaton', 'One might assume WX''s callous nature hides a sensitive inner soul. One would assume incorrectly.', 'EMPATHY MODULE NOT RESPONDING', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/WX-78.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/WX-78.png', 'November 28', 'Butter Muffin', 'Grim', 125, 125, 150);
INSERT INTO survivor VALUES (6, 'Wickerbottom', 'The Librarian', 'A woman of curious mind and stern air, Wickerbottom thrives on the lifelong pursuit of knowledge.', 'Shhhh! No talking!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wickerbottom.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wickerbottom.png', 'December 6', 'Surf ''n'' Turf', 'Grim', 125, 150, 250);
INSERT INTO survivor VALUES (7, 'Woodie', 'The Lumberjack', 'A gruff, bearded woodsman, Woodie has a soft spot for nature, plaid, and his trusty axe, Lucy.', 'That''s a nice lookin'' tree, eh? Not for long.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Woodie.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Woodie.png', 'September 12', 'Honey Nuggets', 'Slim', 150, 150, 200);
INSERT INTO survivor VALUES (8, 'Wes', 'The Silent', 'Wes is a mime of many thoughts, but few words.', '...', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wes.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wes.png', 'April 16', 'Fresh Fruit Crepes', 'None', 75, 75, 75);
INSERT INTO survivor VALUES (9, 'Maxwell', 'The Puppet Master', 'Formerly the Nightmare King, lately Maxwell finds himself reacquainted with life among the commonfolk.', 'Freedom suits me.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Maxwell.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Maxwell.png', 'October 22', 'Wobster Dinner', 'Grim', 75, 150, 200);
INSERT INTO survivor VALUES (10, 'Wigfrid', 'The Performance Artist', 'Whoever Wigfrid was before her titular role has been lost to time, and the power of method acting.', 'All the wörld''s a stage. För me!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wigfrid.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wigfrid.png', 'July 23', 'Turkey Dinner', 'Slim', 200, 120, 120);
INSERT INTO survivor VALUES (11, 'Webber', 'The Indigestible', 'Webber is a polite young monster who cares deeply for all his friends, human or otherwise.', 'We''re always together, and never alone!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Webber.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Webber.png', 'April 30', 'Ice Cream', 'Grim', 175, 175, 100);
INSERT INTO survivor VALUES (12, 'Winona', 'The Handywoman', 'Winona is a former assembly line worker with a boisterous attitude and a love of all things mechanical.', 'Anything can be fixed with hard work and elbow grease.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Winona.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Winona.png', 'September 13', 'Vegetable Stinger', 'Slim', 150, 150, 100);
INSERT INTO survivor VALUES (13, 'Warly', 'The Culinarian', 'To Warly, cooking is a language through which to express love and gratitude to those he holds dear.', 'Nothing worthwhile is ever done on an empty stomach!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Warly.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Warly.png', 'July 25', 'None', 'Grim', 150, 250, 200);
INSERT INTO survivor VALUES (14, 'Wortox', 'The Soul Starved', 'Wortox is a mischievous imp whose levity masks a deep well of guilt. He has taken many souls in his time.', 'Pardon me if I don''t shake your hand.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wortox.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wortox.png', 'March 28', 'Pomegranate', 'Grim', 200, 175, 150);
INSERT INTO survivor VALUES (15, 'Wormwood', 'The Lonesome', 'An amalgam of vines given sentience by lunar magic, Wormwood searches for friends so he can finally belong.', 'Hello friend?', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wormwood.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wormwood.png', 'June 6', 'Cooked Banana', 'Grim', 150, 150, 200);
INSERT INTO survivor VALUES (16, 'Wurt', 'The Half-Pint', 'Wurt is a curious young Merm trying to expand her horizons... as long as those horizons don''t extend into Pig territory.', 'Mermfolk known for hos-per-tality, florp.', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wurt.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wurt.png', 'October 17', 'Durian', 'Slim', 150, 200, 150);
INSERT INTO survivor VALUES (17, 'Walter', 'The Fearless', 'Walter is an odd but cheerful boy, whose ability to assess danger leaves something to be desired.', 'A Pinetree Pioneer is always prepared!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Walter.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Walter.png', 'March 31', 'Trail Mix', 'Slim', 130, 110, 200);
INSERT INTO survivor VALUES (18, 'Wanda', 'The Timekeeper', 'Wanda is a skilled clockmaker who will stop at nothing to outrun her future.', 'Time! I just need more time!', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/icons/Wanda.png', 'https://raw.githubusercontent.com/Juan-Kineipe/dont-starve-together/main/dont-starve-together-ui/src/assets/portraits/Wanda.png', 'August 8', 'Taffy', 'Grim', 80, 175, 200);


INSERT INTO survivor_perks VALUES (1, 1, 'Grows a magnificent beard');
INSERT INTO survivor_perks VALUES (2, 2, 'Has a fondness for fire, but hates the cold');
INSERT INTO survivor_perks VALUES (3, 2, 'Protected by her cuddly bear, Bernie');
INSERT INTO survivor_perks VALUES (4, 2, 'Has a reliable lighter');
INSERT INTO survivor_perks VALUES (5, 3, 'Needs to work out to become mighty');
INSERT INTO survivor_perks VALUES (6, 3, 'Becomes wimpy over time');
INSERT INTO survivor_perks VALUES (7, 3, 'Burns a lot of calories');
INSERT INTO survivor_perks VALUES (8, 3, 'Is afraid of monsters and the dark');
INSERT INTO survivor_perks VALUES (9, 4, 'Is haunted by her twin sister');
INSERT INTO survivor_perks VALUES (10, 4, 'Feels comfortable in the dark');
INSERT INTO survivor_perks VALUES (11, 4, 'Dabbles in Ectoherbology');
INSERT INTO survivor_perks VALUES (12, 4, 'Doesn''t hit very hard');
INSERT INTO survivor_perks VALUES (13, 5, 'Can upgrade with circuits');
INSERT INTO survivor_perks VALUES (14, 5, 'Not a picky eater');
INSERT INTO survivor_perks VALUES (15, 5, 'Is charged by lightning, but damaged by water');
INSERT INTO survivor_perks VALUES (16, 6, 'Knows many things');
INSERT INTO survivor_perks VALUES (17, 6, 'Self publishes books');
INSERT INTO survivor_perks VALUES (18, 6, 'Suffers from insomnia');
INSERT INTO survivor_perks VALUES (19, 6, 'Has a delicate stomach');
INSERT INTO survivor_perks VALUES (20, 7, 'Has a lovely axe...');
INSERT INTO survivor_perks VALUES (21, 7, 'And is at war with the forest');
INSERT INTO survivor_perks VALUES (22, 7, 'Suffers from the curse of the Werebeaver!');
INSERT INTO survivor_perks VALUES (23, 7, 'And the Weremoose and the Weregoose...');
INSERT INTO survivor_perks VALUES (24, 7, 'Is thankful for bountiful harvests');
INSERT INTO survivor_perks VALUES (25, 8, 'Can''t talk');
INSERT INTO survivor_perks VALUES (26, 8, 'Practices Balloonomancy');
INSERT INTO survivor_perks VALUES (27, 8, 'Is not a skilled fighter or worker');
INSERT INTO survivor_perks VALUES (28, 8, 'Has trouble staying alive');
INSERT INTO survivor_perks VALUES (29, 9, 'Is dapper, but frail');
INSERT INTO survivor_perks VALUES (30, 9, 'Can split his mind into pieces');
INSERT INTO survivor_perks VALUES (31, 9, 'Draws power from shadowy equipment');
INSERT INTO survivor_perks VALUES (32, 9, 'Was once the king of the world');
INSERT INTO survivor_perks VALUES (33, 10, 'Excels in battle');
INSERT INTO survivor_perks VALUES (34, 10, 'Absorbs the power of fallen foes');
INSERT INTO survivor_perks VALUES (35, 10, 'Performs well under pressure');
INSERT INTO survivor_perks VALUES (36, 10, 'Only eats meat');
INSERT INTO survivor_perks VALUES (37, 11, 'Is a monster');
INSERT INTO survivor_perks VALUES (38, 11, 'Can befriend spiders');
INSERT INTO survivor_perks VALUES (39, 11, 'Grows a silky smooth beard');
INSERT INTO survivor_perks VALUES (40, 12, 'Is a skilled builder');
INSERT INTO survivor_perks VALUES (41, 12, 'Gets one free hit from the dark');
INSERT INTO survivor_perks VALUES (42, 12, 'Invents her own gadgets');
INSERT INTO survivor_perks VALUES (43, 13, 'Has his own line of custom portable cookware');
INSERT INTO survivor_perks VALUES (44, 13, 'Can spice things up');
INSERT INTO survivor_perks VALUES (45, 13, 'Has an insatiable appetite');
INSERT INTO survivor_perks VALUES (46, 13, 'Only eats gourmet food');
INSERT INTO survivor_perks VALUES (47, 14, 'Is an imp');
INSERT INTO survivor_perks VALUES (48, 14, 'Can hop through time and space');
INSERT INTO survivor_perks VALUES (49, 14, 'Less nourished by physical food');
INSERT INTO survivor_perks VALUES (50, 15, 'Plants relate to him');
INSERT INTO survivor_perks VALUES (51, 15, 'Saddened when plants are killed');
INSERT INTO survivor_perks VALUES (52, 15, 'Has a Green Thumb');
INSERT INTO survivor_perks VALUES (53, 15, 'Food fills his stomach, but not his heart');
INSERT INTO survivor_perks VALUES (54, 16, 'At home in the swamp');
INSERT INTO survivor_perks VALUES (55, 16, 'Has big plans for Merm-kind');
INSERT INTO survivor_perks VALUES (56, 16, 'Is a vegetarian');
INSERT INTO survivor_perks VALUES (57, 17, 'Not afraid of anything, except getting hurt');
INSERT INTO survivor_perks VALUES (58, 17, 'Good with a slingshot');
INSERT INTO survivor_perks VALUES (59, 17, 'Has a four-legged friend');
INSERT INTO survivor_perks VALUES (60, 17, 'Allergic to bees');
INSERT INTO survivor_perks VALUES (61, 17, 'Has no interest in fashion');
INSERT INTO survivor_perks VALUES (62, 18, 'Has excellent time management skills');
INSERT INTO survivor_perks VALUES (63, 18, 'Only as old as she feels');
INSERT INTO survivor_perks VALUES (64, 18, 'In a constant race against the clock');
